<?php

// This file has been auto-generated by the Symfony Dependency Injection Component for internal use.

if (\class_exists(\ContainerAy2th8K\srcApp_KernelDevDebugContainer::class, false)) {
    // no-op
} elseif (!include __DIR__.'/ContainerAy2th8K/srcApp_KernelDevDebugContainer.php') {
    touch(__DIR__.'/ContainerAy2th8K.legacy');

    return;
}

if (!\class_exists(srcApp_KernelDevDebugContainer::class, false)) {
    \class_alias(\ContainerAy2th8K\srcApp_KernelDevDebugContainer::class, srcApp_KernelDevDebugContainer::class, false);
}

return new \ContainerAy2th8K\srcApp_KernelDevDebugContainer([
    'container.build_hash' => 'Ay2th8K',
    'container.build_id' => '4d27eeb9',
    'container.build_time' => 1573339315,
], __DIR__.\DIRECTORY_SEPARATOR.'ContainerAy2th8K');
