<?php

// This file has been auto-generated by the Symfony Routing Component.

return [
    'app_empresa_novaempresa' => [[], ['_controller' => 'App\\Controller\\EmpresaController::novaEmpresa'], [], [['text', '/empresas/create']], [], []],
    'app_empresa_login' => [[], ['_controller' => 'App\\Controller\\EmpresaController::login'], [], [['text', '/empresas/login']], [], []],
    'app_empresa_atualizar' => [[], ['_controller' => 'App\\Controller\\EmpresaController::atualizar'], [], [['text', '/empresas/update']], [], []],
    'app_empresa_pesquisaatestados' => [[], ['_controller' => 'App\\Controller\\EmpresaController::pesquisaAtestados'], [], [['text', '/empresas/atestados']], [], []],
    'app_medico_novomedico' => [[], ['_controller' => 'App\\Controller\\MedicoController::novoMedico'], [], [['text', '/medicos/create']], [], []],
    'app_medico_login' => [[], ['_controller' => 'App\\Controller\\MedicoController::login'], [], [['text', '/medicos/login']], [], []],
    'app_medico_atualizar' => [[], ['_controller' => 'App\\Controller\\MedicoController::atualizar'], [], [['text', '/medicos/update']], [], []],
    'app_medico_criaatestado' => [[], ['_controller' => 'App\\Controller\\MedicoController::criaAtestado'], [], [['text', '/medicos/atestados']], [], []],
    'app_medico_validaatestado' => [[], ['_controller' => 'App\\Controller\\MedicoController::validaAtestado'], [], [['text', '/medicos/atestados']], [], []],
    'app_paciente_novopaciente' => [[], ['_controller' => 'App\\Controller\\PacienteController::novoPaciente'], [], [['text', '/pacientes/create']], [], []],
    'app_paciente_login' => [[], ['_controller' => 'App\\Controller\\PacienteController::login'], [], [['text', '/pacientes/login']], [], []],
    'app_paciente_buscaratestados' => [[], ['_controller' => 'App\\Controller\\PacienteController::buscarAtestados'], [], [['text', '/pacientes/atestados']], [], []],
];
